calculation-operation PR
gilberthappi/math-magicians pull request #3
Opened 2023-09-28 07:23 UTC by gilberthappi

Handle events in a React app.
Use React life cycle methods.
Understand the mechanism of lifting state up.
Use React state.

2023-09-28 09:12 UTC, prolajumokeoni requested changes
Hi @gilberthappi 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  Correct operate.js and calculate.js files

✔️ Calculator works correctly

✔️ % button should work as modulus



## Required Changes ♻️

- [ ] It would be better to add the Table of Contents section in your readme so it is easy to navigate to different sections in your readme 👍🏿  

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-28 09:12 UTC, prolajumokeoni commented on src/components/Calculator.js
> +          <button className="evaluationBtn" type="button" onClick={this.clickHandler}>=</button>
-  Based on the requirements,  your  Calculator.js should have at least 1 child component ⬇️ 

- [ ] Kindly make sure that props are passed correctly  from the Calculator.js component to the child component, this will help you practice   what you have learned in `props` and  organize your UI into smaller, reusable pieces,  making your codebase more maintainable & easier to understand 👍

2023-09-28 09:12 UTC, prolajumokeoni commented on src/logic/operate.js
> +// eslint-disable-next-line import/no-extraneous-dependencies
- [ ] Kindly avoid disabling linters as it is not a good practice, it is better for your linters to pass the linter checks 👍🏿

2023-09-29 08:48 UTC, roshan-bajgain approved these changes
Hi @gilberthappi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- Gitflow is followed. ✔️
- Good job on changing the requested ✔️ 

## Optional suggestions
- [ ] As requested by previous reviewer please make sure to add Table of Contents section in your Readme file so It would be more professional.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-29 08:48 UTC, roshan-bajgain commented on src/components/Calculator.js
> +  }
- [ ] [Optional] I would suggest you please use the functional component in place of the class-based component.

2023-09-29 11:06 UTC, merged